name = "local-video-clip-editor-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "videoclip-db"
database_id = "85d645e3-0c48-4609-87ba-24bf0e30ebb8"
migrations_dir = "migrations"

[vars]
GOOGLE_CLIENT_ID = ""
APP_URL = "https://local-video-clip-editor-worker.varmaabhishek97.workers.dev"
FRONTEND_URL = "https://local-video-clip-editor.varmaabhishek97.workers.dev"

[dev]
port = 8787
local_protocol = "http"
