name = "local-video-clip-editor-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "videoclip-db"
database_id = "85d645e3-0c48-4609-87ba-24bf0e30ebb8"
migrations_dir = "migrations"

[vars]
GOOGLE_CLIENT_ID = "602559584843-l6c118m3cg9ff91u79p3r5gfhjkkadie.apps.googleusercontent.com"
APP_URL = "https://local-video-clip-editor-worker.varmaabhishek97.workers.dev"
FRONTEND_URL = "https://local-video-clip-editor.varmaabhishek97.workers.dev"
FACEBOOK_APP_ID = "1837775677343013"
META_GRAPH_API_VERSION = "v26.0"
B2_BUCKET_NAME = "videoclip-reels-3c4861c9d0db"
B2_BUCKET_ID = "53bc741806513c89ad000d1b"


[dev]
port = 8787
local_protocol = "http"

[triggers]
crons = ["* * * * *"]

