
name = "local-video-clip-editor-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "videoclip-db"
database_id = ""
migrations_dir = "migrations"

[vars]
GOOGLE_CLIENT_ID = ""
APP_URL = "https://commission-promotes-prizes-implied.trycloudflare.com"
FRONTEND_URL = "http://localhost:3000"

[dev]
port = 8787
local_protocol = "http"

[triggers]
crons = ["0 3 * * *"]


